### ISSUE TITLE
Not showing all achievements

### ISSUE THREAD

**Issue by deryilz** [Prouser123/xbl-web-api#7]
It seems to stop at 32 on the `/achievements/1/titleprogress/<int:xuid>/<int:titleid>` option. Can I fix this?

**Comment by jcxldn** [comment]
Fixed & deployed as part of #10.

`?continuationToken=(int)` now works as expected.

eg: `/achievements/1/titleprogress/<int:xuid>/<int:titleid>?continuationToken=32`

I hope this helps!

Thanks

-James

@DerDer56
